// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_0xOqN-BHZW5QHcr31uKxYvv7lCXqRU',
    appId: '1:360639631772:web:cd25b9f653ecf9f635f859',
    messagingSenderId: '360639631772',
    projectId: 'chatme-9c314',
    authDomain: 'chatme-9c314.firebaseapp.com',
    databaseURL: 'https://chatme-9c314-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-9c314.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Jw9W1cBmX783wZaWyIA_mCJdI81UkPM',
    appId: '1:360639631772:android:22f5dbd6400315dc35f859',
    messagingSenderId: '360639631772',
    projectId: 'chatme-9c314',
    databaseURL: 'https://chatme-9c314-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-9c314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmcsshQZey-srmnarBlVxRxy9p0OH0NXY',
    appId: '1:360639631772:ios:d6ae07542c39349735f859',
    messagingSenderId: '360639631772',
    projectId: 'chatme-9c314',
    databaseURL: 'https://chatme-9c314-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-9c314.firebasestorage.app',
    iosBundleId: 'com.example.dream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmcsshQZey-srmnarBlVxRxy9p0OH0NXY',
    appId: '1:360639631772:ios:d6ae07542c39349735f859',
    messagingSenderId: '360639631772',
    projectId: 'chatme-9c314',
    databaseURL: 'https://chatme-9c314-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-9c314.firebasestorage.app',
    iosBundleId: 'com.example.dream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi_0xOqN-BHZW5QHcr31uKxYvv7lCXqRU',
    appId: '1:360639631772:web:1ad79492bb3aac4035f859',
    messagingSenderId: '360639631772',
    projectId: 'chatme-9c314',
    authDomain: 'chatme-9c314.firebaseapp.com',
    databaseURL: 'https://chatme-9c314-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-9c314.firebasestorage.app',
  );
}
